# Generated by Django 6.1.1 on 2026-09-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stockanalysis',
            name='feedback',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PortfolioAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
                ('number_of_stocks', models.IntegerField()),
                ('number_of_sectors', models.IntegerField()),
                ('diversification_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=50)),
                ('hhi', models.FloatField()),
                ('largest_holding', models.JSONField(default=dict)),
                ('largest_sector', models.JSONField(default=dict)),
                ('holding_breakdown', models.JSONField(default=list)),
                ('sector_breakdown', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='portfolios.portfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
