# Generated by Django 6.1.1 on 2026-09-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_portfolioanalysishistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockanalysis',
            name='stock',
        ),
        migrations.DeleteModel(
            name='PortfolioAnalysis',
        ),
        migrations.DeleteModel(
            name='StockAnalysis',
        ),
    ]
