# Generated by Django 6.1.1 on 2026-09-11 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='FundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_holdings', to='portfolios.fund')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_holdings', to='stocks.stock')),
            ],
            options={
                'unique_together': {('fund', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='FundSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=150)),
                ('weight', models.FloatField()),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_sectors', to='portfolios.fund')),
            ],
            options={
                'unique_together': {('fund', 'sector')},
            },
        ),
    ]
